// Public identifiers only (no secrets). Generated by `npm run env` in web/ from the stack outputs.
export const config = {
  apiUrl: import.meta.env.VITE_API_URL as string,
  userPoolId: import.meta.env.VITE_USER_POOL_ID as string,
  userPoolClientId: import.meta.env.VITE_USER_POOL_CLIENT_ID as string,
  repoUrl: "https://github.com/navneet-cerecode/tanksaathi",
};
